sudo: false
language: ruby
rvm: 2.4.1
cache:
  - bundler
  - pip
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production
install:
  - gem install jekyll
  - pip install --user awscli
  - pip install --user s3cmd
script:
  - bundle install
  - bundle exec jekyll build
  - bundle exec rake site:test
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: courses.tss-yonder.com
  region: eu-central-1
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  cache_control: "max-age=900"
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
