sudo: false
language: ruby
cache: bundler
rvm: 2.4.0
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production
install:
    - gem install jekyll
    - gem install s3_website
script:
  - bundle install
  - bundle exec jekyll build
  - bundle exec rake site:test
after_success: s3_website push
