sudo: false
language: ruby
cache: bundler
rvm: 2.4.0
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production
install:
    - gem install jekyll
script:
  - bundle install
  - bundle exec jekyll build
  - bundle exec rake site:test
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: courses.tss-yonder.com
  region: eu-central-1
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  cache_control: "max-age=900"
