# Site Settings
title: Cursuri susținute de TSS-Yonder
url: "https://courses.tss-yonder.com"
baseurl: ""
paginate_path: resurse/pagina-:num/
permalink: resurse/:categories/:title/
force-https: True
lang: "ro"
paginate: 5
google-tracking-id: "UA-99139394-1"
theme: "prettydocs-jekyll"

# Build Settings
github:             [metadata]
encoding:           UTF-8 
markdown:           kramdown
highlighter:        none
kramdown:
  input:            GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  syntax_highlighter_opts:
    disable : true

# Enable minification SASS
sass:
  sass_dir:         assets/css
  style:            compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Theme settings
author:
  name: "TSS-Yonder"
  email: ""
  website:
    url: " https://tss-yonder.com/"
    title: ""

# Shower default values
default_width: 792
default_lang: en
default_body_class: list

exclude:
  - CONTRIBUTING
  - CONTRIBUTORS
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor
  - .gitignore
  - .travis.yml
  - .build

# Settings for build and deploy
production_url:     "https://courses.tss-yonder.com/"
